# ================================
# Azure DevOps Pipeline for SpecFlow
# ================================

trigger:
- main  # Automatic build on push

parameters:
- name: runRelease
  type: boolean
  default: false  # Set true when manually triggering Release stage
- name: testTags
  type: string
  default: 'Regression'  # Default tags, comma-separated for multiple

pool:
  vmImage: 'windows-latest'

stages:
# ===========================
# Stage 1: Automatic Build
# ===========================
- stage: Build
  displayName: 'Automatic Build'
  jobs:
  - job: BuildJob
    displayName: 'Build and Run Tests'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    # Run all automation tests (optional in build)
    - task: VSTest@2
      inputs:
        platform: 'Any CPU'
        configuration: 'Release'
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*Tests.dll'
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

# ===========================
# Stage 2: Manual Release
# ===========================
- stage: Release
  displayName: 'Manual Release'
  condition: eq(${{ parameters.runRelease }}, true)  # Only runs when manually triggered
  jobs:
  - job: ManualReleaseJob
    displayName: 'Run SpecFlow Tests by Tags'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    # Run SpecFlow tests filtered by tags
    - task: VSTest@2
      displayName: 'Run SpecFlow Tests by Tags'
      inputs:
        platform: 'Any CPU'
        configuration: 'Release'
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\*Tests.dll'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        testFiltercriteria: 'TestCategory in (${{ parameters.testTags }})'  # multiple tags: comma-separated

    # Publish test results
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/TestResults/*.trx'
        mergeTestResults: true