# Final Azure Pipelines YAML for Build + Regression (mimics company setup)

trigger:
  - main   # CI: runs automatically when code is pushed to main

parameters:
  - name: runRegression
    type: boolean
    default: false  # set to true when you want to run regression manually/scheduled

pool:
  vmImage: 'windows-latest'

# ----------------------------
# Stage 1: Build (always runs)
# ----------------------------
stages:
- stage: Build
  displayName: 'Build Stage (CI)'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '7.x'

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      - task: VSBuild@1
        inputs:
          solution: '**/*.sln'
          platform: 'Any CPU'
          configuration: 'Release'

      # Publish artifacts for next stage (like company release)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
          publishLocation: 'Container'

# ----------------------------
# Stage 2: Regression (manual / scheduled)
# ----------------------------
- stage: Regression
  displayName: 'Regression Suite (acts as Release)'
  condition: eq('${{ parameters.runRegression }}', true)  # only runs if you enable it
  dependsOn: Build
  jobs:
  - job: RegressionJob
    displayName: 'Run Regression Tests'
    steps:
      - task: VSTest@2
        inputs:
          testAssemblyVer2: '**\*Tests*.dll'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          platform: 'Any CPU'
          configuration: 'Release'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/*.trx'
          mergeTestResults: true