# ----------------------------
# Build & Regression Test Stage
# ----------------------------
stages:
- stage: BuildAndTest
  displayName: 'Build and Run Regression Tests'
  jobs:
  - job: BuildAndRegression
    displayName: 'Build & Regression Test Job'
    pool:
      vmImage: 'windows-latest'
    steps:
      # 1️⃣ Install .NET SDK
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '7.x'

      # 2️⃣ Restore NuGet packages
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      # 3️⃣ Build solution
      - task: VSBuild@1
        inputs:
          solution: '**/*.sln'
          platform: 'Any CPU'
          configuration: 'Release'

      # 4️⃣ Run SpecFlow NUnit tests with Regression tag
      - task: DotNetCoreCLI@2
        displayName: 'Run Regression Tests'
        inputs:
          command: 'test'
          projects: '**/*Tests/*.csproj'   # Adjust if your test project path is different
          arguments: '--configuration Release --filter "TestCategory=Regression" --logger "trx;LogFileName=test_results.trx"'

      # 5️⃣ Publish test results to Azure DevOps
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/test_results.trx'
          mergeTestResults: true

      # 6️⃣ Optional: publish artifacts
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
          publishLocation: 'Container'
