# Azure Pipelines YAML for C# SpecFlow Project
trigger:
  - main   # automatic build when code is pushed to main

parameters:
  - name: runRelease
    type: boolean
    default: false
  - name: testTags
    type: string
    default: 'Regression'  # default tag to run

pool:
  vmImage: 'windows-latest'

stages:
# ----------------------------
# Build & Test Stage (Automatic)
# ----------------------------
- stage: Build
  displayName: 'Automatic Build & Run Tests'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test Job'
    steps:
      # Install .NET SDK
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '7.x'

      # Install NuGet tool
      - task: NuGetToolInstaller@1

      # Restore NuGet packages
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      # Build solution
      - task: VSBuild@1
        inputs:
          solution: '**/*.sln'
          platform: 'Any CPU'
          configuration: 'Release'

      # Run SpecFlow / automation tests
      - task: VSTest@2
        inputs:
          platform: 'Any CPU'
          configuration: 'Release'
          testAssemblyVer2: '**\*Tests*.dll'   # adjust if your test assembly name is different
          searchFolder: '$(System.DefaultWorkingDirectory)'
          testFiltercriteria: 'TestCategory=$(testTags)'  # run only tests with this tag

      # Explicitly publish test results (backup, ensures Tests tab always shows results)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/*.trx'
          mergeTestResults: true

      # Publish artifacts for manual release
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'
          publishLocation: 'Container'

# ----------------------------
# Release Stage (Manual)
# ----------------------------
- stage: Release
  displayName: 'Manual Release'
  condition: eq('${{ parameters.runRelease }}', true)  # only runs when manually triggered
  jobs:
  - job: ManualReleaseJob
    displayName: 'Manual Release Job'
    steps:
      - script: |
          echo "Manual release stage. Trigger manually when needed."
          echo "You can also deploy or run additional tasks here."